version: '3.3'

services:

  glaciar-org-front:
    container_name: glaciar.org-front
    image: glaciar/glaciar.org-front:1.2
    ports:
      - '80:80'
    networks:
      - network-front
    secrets:
      - source: env_docker_file
        target: /app/.env
        mode: 0400 


  glaciar-org-back:
    container_name: glaciar.org-back
    image: glaciar/glaciar.org-back:1.1
    # volumes:
    #   - '.env_docker:/app/.env'
    ports:
      - '3000:5000'
    networks:
      - network-front
      - network-back
    depends_on:
      - glaciar-mongo
    secrets:
      - env_docker_file


  glaciar-mongo:
    image: mongo:4.0
    container_name: glaciar-mongo
    volumes:
      # named volumes
      - mongodb:/data/db
      - mongoconfig:/data/configdb
    ports:
      - "27018:27017"
    networks:
      - network-back


volumes:
  # default dir on Ubuntu: /var/lib/docker/volumes
  mongodb:
  mongoconfig:


secrets:
  env_docker_file:
    - file: .env_docker

networks:
  default:
    driver: overlay
  network-front:
    driver: overlay
  network-back:
    driver: overlay


#
# Runtime (t needs .env_docker)
#    docker-compose -f docker-compose-glaciar.org.yml up --build
#    docker-compose -f docker-compose-glaciar.org.yml down --volumes
